### ISSUE TITLE
Search bar  not getting info

### ISSUE THREAD

**Issue by melsil11** [sei-ec-remote/team-project-issues#117]
**Describe the bug**
_A clear and concise description of what the bug is._
I have a search bar that is not hitting the axios call and filtering the information from the call

**What is the problem you are trying to solve?**
I wan the function to get the data from the axios get call /restaurants and filter through to find restaurants

**Expected behavior**
_A clear and concise description of what you expected to happen._
I expected the function to get the data from the call and filter through the data to find matching data 

**What is the actual behavior?**
_A clear and concise description of what actually happened._
It is not getting the data from the axios call

**Post any code you think might be relevant (one fenced block per file)**
```
Search Bar file

import React, { useState, useEffect} from "react"
// import ".src/index.css"
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faXmark, faMagnifyingGlass } from '@fortawesome/free-solid-svg-icons'
import axios from "axios"
import {Input, Space, Button} from 'antd'


const {Search} = Input
const SearchBar = () => {
    const [data, setData] = useState([])
    const [filteredData, setFilteredData] = useState([])
    const [error, setError] = useState("")
    const [input, setInput] = useState("")
    console.log('I hit here')
    useEffect(() => {
        console.log('I tried to hit here')
      axios.get('/reataurants')
        .then((response) => {
        console.log('a little bit farther down')
        console.log(response.data)
        setData(response.data)
        setFilteredData(response.data)
    })
    .catch((err) => {
      console.log(err)
      setError(err)
    })
}, [])
const handleFilter = (e) => {
  console.log(e)
  const searchInput = e.target.value
  setInput(searchInput)
  const newFilter = data.filter((value) => {
  return  value.name.toLowerCase().includes(searchInput.toLowerCase())
})
  if (searchInput === "") {
    setFilteredData([])
  } else {
    setFilteredData(newFilter)
  }
}
return(
  <div className="search">
    <div className="searchInputs">
      <Search
        placeholder="Search for a Restaurant" 
        value={input}
        onChange={(e) => handleFilter(e)}       
        enterButton 
      />
    </div>
      {filteredData.length != 0 && (
    <div className="dataResult">
      {filteredData.slice(0, 10).map((value, index) => {
      return (
      <div className="dataItem" key={value.id}>
        <p>{value.name}</p>
      </div>
      )
    })}
    </div>
    )}
  </div>
 )
}

export default SearchBar

Axios call file

import apiUrl from '../apiConfig'
import axios from 'axios'

export const SearchBar = (data) => {
	return axios({
		method: 'GET',
		url: apiUrl + '/restaurants',
        data: {
			restaurant: data,
		},
	})
}

// export const SearchBar= (user) => {
// 	return axios({
// 		method: 'GET',
// 		url: apiUrl + '/restaurants'
// 	})
// }


nav bar file 
		<Nav.Item className='m-2'>
			<SearchBar placeholder='Search a restaurant'/>
		</Nav.Item>
```

**What is your best guess as to the source of the problem?**

It is not. grabbing the right information

**What things have you already tried to solve the problem?**
I tried creating a seperate axios call in a new file, I have changed the values in the function. I have console.logged to see what it is and isn't hitting

**Additional context**

**Paste a link to your repository here**[
](https://github.com/sam-phillips21/Client-theGoodAvocado)

**Comment by ejparnell** [comment]
@melsil11 What errors are you running into? Are you getting a 404? or a 422? When you say it's not grabbing the right information is it grabbing any information?

**Comment by melsil11** [comment]
If I type in the search bar there are no errors, I can see the onchange as I type and the first console.log that I have for testing.  If I refresh the page I see the second console.log I have for testing.

**Comment by melsil11** [comment]
I moved the console.log and it didn't like it and when the page refreshed I got a axios 404 error
```
{
    "message": "Request failed with status code 404",
    "name": "AxiosError",
    "stack": "AxiosError: Request failed with status code 404\n    at settle (http://localhost:3000/static/js/bundle.js:90386:12)\n    at XMLHttpRequest.onloadend (http://localhost:3000/static/js/bundle.js:89126:66)",
    "config": {
        "transitional": {
            "silentJSONParsing": true,
            "forcedJSONParsing": true,
            "clarifyTimeoutError": false
        },
        "transformRequest": [
            null
        ],
        "transformResponse": [
            null
        ],
        "timeout": 0,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "env": {},
        "headers": {
            "Accept": "application/json, text/plain, */*"
        },
        "method": "get",
        "url": "/reataurants"
    },
    "code": "ERR_BAD_REQUEST",
    "status": 404
}

**Comment by melsil11** [comment]
added onSearch function 
```
const onSearch = (searchInput) => {
    const newFilter = data.restaurants.filter((value) => {
        return  value.name.toLowerCase().includes(searchInput.toLowerCase())
    })
    console.log('new filter', newFilter)
}
