### ISSUE TITLE
AWS/Multer Upload Error

### ISSUE THREAD

**Issue by estebbins** [sei-ec-remote/team-project-issues#133]
**Describe the bug**
_A clear and concise description of what the bug is._
Failing to upload file with AWS/multer

**What is the problem you are trying to solve?**
Uploading a file...seem to be missing a file path from req.file.path

**Expected behavior**
_A clear and concise description of what you expected to happen._

**What is the actual behavior?**
_A clear and concise description of what actually happened._
```json
{
    "error": "Failed to upload file"
}
```

**Post any code you think might be relevant (one fenced block per file)**
```js
router.post('/files', upload.single('file'), async (req, res) => { 
    try { 
        console.log('params', req.params)
        console.log('req.body', req.body)
        console.log('req.body.file', req.body.file)
        console.log('req.file', req.file)
        console.log('req.file.path', req.file.path)
        const fileUrl = await s3Upload(req.file.path, req.file.originalname) 
        res.json({ url: fileUrl }) 
    } 
    catch (err) { 
        console.log('req.body.file', req.body.file)
        console.log('req.file', req.file)
        console.error(err) 
        res.status(500).json({ error: 'Failed to upload file' }) 
    } 
})

```
```js
require('dotenv').config()

const AWS = require('aws-sdk')
const uuid = require('uuid')
const s3 = new AWS.S3({ 
    accessKeyId: process.env.AWS_ACCESS_KEY_ID, 
    secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY, 
    region: process.env.AWS_REGION
})
const fs = require('fs');
const path = require('path');

const uploadFileToS3 = async (filePath, key) => {
    const fileStream = fs.createReadStream(filePath);
  
    const uploadParams = {
      Bucket: process.env.AWS_BUCKET_NAME,
      Key: key,
      Body: fileStream,
    };
  
    const result = await s3.upload(uploadParams).promise();
  
    fs.unlinkSync(filePath);
  
    return result.Location;
  };
  
            
module.exports = uploadFileToS3 
```

**What is your best guess as to the source of the problem?**
Multer middleware/filepath requirement 

**What things have you already tried to solve the problem?**
switched from JSON for req.body to using form data in postman

**Additional context**

**Paste a link to your repository here**
https://github.com/estebbins/hoistm-api/tree/aws

**Comment by timmshinbone** [comment]
Share the results of the console log for `req.file`

**Comment by estebbins** [comment]
```
req.file {
  fieldname: 'file',
  originalname: 'bothcats.jpeg',
  encoding: '7bit',
  mimetype: 'image/jpeg',
  buffer: <Buffer ff d8 ff e0 00 10 4a 46 49 46 00 01 02 00 00 01 00 01 00 00 ff ed 00 9c 50 68 6f 74 6f 73 68 6f 70 20 33 2e 30 00 38 42 49 4d 04 04 00 00 00 00 00 80 ... 183200 more bytes>,
  size: 183250
}
```

**Comment by timmshinbone** [comment]
What's the different between `req.file` and `req.body.file`?

**Comment by estebbins** [comment]
There is actually no req.body with the form-data, it returns req.file. req.body.file is undefined

**Comment by timmshinbone** [comment]
ok, can you share a link to where it says you need the path? probably gonna be the s3 docs

**Comment by estebbins** [comment]
We looked into more documentation and found that we probably needed to use multer-s3, and match our versions of AWS & multer-s3, which we are now using. We've now successfully connected to AWS, but are getting this error that we're now trying to resolve: 
```
file {
  fieldname: 'file',
  originalname: 'bothcats.jpeg',
  encoding: '7bit',
  mimetype: 'image/jpeg'
}

 12:07:12 GMT-0500 (Eastern Standard Time):
AccessDenied: Access Denied
    at throwDefaultError (/Users/emilystebbins/sei_fruitcakes/projects/project-3/api-project-3/node_modules/@aws-sdk/client-s3/node_modules/@aws-sdk/smithy-client/dist-cjs/default-error-handler.js:8:22)
    at deserializeAws_restXmlPutObjectCommandError (/Users/emilystebbins/sei_fruitcakes/projects/project-3/api-project-3/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:5782:43)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/emilystebbins/sei_fruitcakes/projects/project-3/api-project-3/node_modules/@aws-sdk/client-s3/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
    at async /Users/emilystebbins/sei_fruitcakes/projects/project-3/api-project-3/node_modules/@aws-sdk/client-s3/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:14:20
    at async /Users/emilystebbins/sei_fruitcakes/projects/project-3/api-project-3/node_modules/@aws-sdk/client-s3/node_modules/@aws-sdk/middleware-retry/dist-cjs/retryMiddleware.js:27:46
    at async /Users/emilystebbins/sei_fruitcakes/projects/project-3/api-project-3/node_modules/@aws-sdk/middleware-flexible-checksums/dist-cjs/flexibleChecksumsMiddleware.js:58:20
    at async /Users/emilystebbins/sei_fruitcakes/projects/project-3/api-project-3/node_modules/@aws-sdk/client-s3/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:5:22
    at async Promise.all (index 0)
    at async Upload.__uploadUsingPut (/Users/emilystebbins/sei_fruitcakes/projects/project-3/api-project-3/node_modules/@aws-sdk/lib-storage/dist-cjs/Upload.js:66:26) {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 403,
    requestId: 'HMQBWJXC6V4CA21B',
    extendedRequestId: 'ahO1+PhB/xySCh2TKj/Cwjz71TXZW0L++6CBf4MYvXfi/YTYrfEyvOsvguD+WylF0akvmRJhBM4=',
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  Code: 'AccessDenied',
  RequestId: 'HMQBWJXC6V4CA21B',
  HostId: 'ahO1+PhB/xySCh2TKj/Cwjz71TXZW0L++6CBf4MYvXfi/YTYrfEyvOsvguD+WylF0akvmRJhBM4=',
  storageErrors: []
}
```

**Comment by estebbins** [comment]
We believe it is probably an AWS permissions issue but haven't been able to resolve yet.

**Comment by timmshinbone** [comment]
yeah, 403 forbidden might have to do with how you load in/pass your key to multer-s3. Wanna share link to docs for multer-s3 for me?

**Comment by estebbins** [comment]
https://github.com/anacronw/multer-s3#readme 

```js
const multer = require('multer')
const multerS3 = require('multer-s3')
const aws = require('@aws-sdk/client-s3')

const s3 = new aws.S3Client({ 
    accessKeyId: process.env.AWS_ACCESS_KEY_ID, 
    secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY, 
    region: process.env.AWS_REGION
})
const upload = multer({
    storage: multerS3({
        s3: s3,
		acl: 'public-read',
        bucket: 'hoistm-cloud-system',
        key: function (req, file, cb) {
            console.log('file', file)
            cb(null, file.originalname); //use Date.now() for unique file keys
        }
    })
})
const s3Upload = require('../../lib/s3_upload')

router.post('/files', upload.single('file'), function (req, res, next) {
    res.send({
			message: "Uploaded!",
			url: function(file) {
				return {url: file.location, name: file.key, type: file.mimetype, size: file.size}
			}
		})
})
```

**Comment by timmshinbone** [comment]
interesting, reading over them now, will get back to you on it

**Comment by estebbins** [comment]
We needed to create a group on AWS, add a user, and then give the user permission on AWS.
