### ISSUE TITLE
.env Issue

### ISSUE THREAD

**Issue by Jlarranaga** [sei-ec-remote/team-project-issues#175]
**Describe the bug**
_A clear and concise description of what the bug is._

Terminal is saying .env file has an keyerror

**What is the problem you are trying to solve?**

get .en file to work properly

**Expected behavior**
_A clear and concise description of what you expected to happen._
need to use env file for access to database

**What is the actual behavior?**
_A clear and concise description of what actually happened._

**Post any code you think might be relevant (one fenced block per file)**
```js
Traceback (most recent call last):
  File "/home/jacob/.local/lib/python3.10/site-packages/environ/environ.py", line 388, in get_value
    value = self.ENVIRON[var_name]
  File "/usr/lib/python3.10/os.py", line 680, in __getitem__
    raise KeyError(key) from None
KeyError: 'PASSWORD'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jacob/sei/django-env/Projects/Project3-DreamHues/Project3DreamHues/manage.py", line 22, in <module>
    main()
  File "/home/jacob/sei/django-env/Projects/Project3-DreamHues/Project3DreamHues/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3/dist-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3/dist-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python3/dist-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python3/dist-packages/django/core/management/commands/runserver.py", line 61, in execute
    super().execute(*args, **options)
  File "/usr/lib/python3/dist-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python3/dist-packages/django/core/management/commands/runserver.py", line 68, in handle
    if not settings.DEBUG and not settings.ALLOWED_HOSTS:
  File "/usr/lib/python3/dist-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/usr/lib/python3/dist-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/lib/python3/dist-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/jacob/sei/django-env/Projects/Project3-DreamHues/Project3DreamHues/Project3DreamHues/settings.py", line 86, in <module>
    'PASSWORD': env('PASSWORD'),
  File "/home/jacob/.local/lib/python3.10/site-packages/environ/environ.py", line 199, in __call__
    return self.get_value(
  File "/home/jacob/.local/lib/python3.10/site-packages/environ/environ.py", line 392, in get_value
    raise ImproperlyConfigured(error_msg) from exc
django.core.exceptions.ImproperlyConfigured: Set the PASSWORD environment variable
```

**What is your best guess as to the source of the problem?**

Not sure, maybe env file is being read wrong

**What things have you already tried to solve the problem?**

Team member collab, google 

**Additional context**

**Paste a link to your repository here**
https://github.com/Jlarranaga/Project3-DreamHues

**Comment by nayaba** [comment]
How are you using your environment variables in your settings file?

**Comment by Jlarranaga** [comment]
`DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('NAME'),
        'USER': env('USER'),
        'PASSWORD': env('PASSWORD'),
        'HOST': env('HOST'),
        'PORT': env('PORT'),
        'OPTIONS': {'sslmode': 'require'},
    }
}`

**Comment by Jlarranaga** [comment]
![image](https://github.com/sei-ec-remote/team-project-issues/assets/149622991/c9c4fdb9-1344-40e1-ac47-a6031f1c10cc)

**Comment by Jlarranaga** [comment]
![image](https://github.com/sei-ec-remote/team-project-issues/assets/149622991/fd6f81e2-f58e-4143-92f1-211a188b2b9d)

**Comment by nayaba** [comment]
Is this happening on everyone's machine?  My first guess is that something is improperly formatted with the PASSWORD value on the env file

**Comment by Jlarranaga** [comment]
Yeah its everyone's

**Comment by Jlarranaga** [comment]
![image](https://github.com/sei-ec-remote/team-project-issues/assets/149622991/a70076b6-3bbb-4207-a9ba-89d8472407f6)

**Comment by nayaba** [comment]
Can you get rid of options?

**Comment by nayaba** [comment]
I'm deleting your last comment so the env info isn't public, but the file looks properly formatted

**Comment by Jlarranaga** [comment]
Ok thank you, and let me try that

**Comment by Jlarranaga** [comment]
I commented it out and still didnt work

**Comment by Jlarranaga** [comment]
![image](https://github.com/sei-ec-remote/team-project-issues/assets/149622991/7ce9abbd-fc0c-4a34-9c9e-849f8fb6f166)

**Comment by Jlarranaga** [comment]
For the project I accidently added an extra folder layer. Would that mess with the env file being an extra layer higher?

**Comment by nayaba** [comment]
It could - the env file needs to be at the same level as manage.py

**Comment by Jlarranaga** [comment]
Yeah, it's on the same level
![image](https://github.com/sei-ec-remote/team-project-issues/assets/149622991/faf68a9c-ebdd-4703-9307-80ed92832e08)

**Comment by Jlarranaga** [comment]
So I'm reading we need to set the variables. And online it says set the variables in the terminal? But we do that everytime?

**Comment by nayaba** [comment]
You shouldn't have to do that every time.

**Comment by Jlarranaga** [comment]
FIXED! .env file needs to be in the same folder as settings.py
