### ISSUE TITLE
Cannot create service document in Postman (it is not letting us associate a user with it)

### ISSUE THREAD

**Issue by alysarnau** [sei-ec-remote/team-project-issues#45]
**Describe the bug**
_A clear and concise description of what the bug is._
When I try to run the createService route, it gives me a 500 internal server error and the following terminal message:
```
 14:19:29 GMT-0400 (Eastern Daylight Time):
TypeError: Cannot set properties of undefined (setting 'owner')
    at /home/alys/sei_ice_pops/projects/Project3App/Project_3_Api/project_3_api/app/routes/service_routes.js:65:25
    at Layer.handle [as handle_request] (/home/alys/sei_ice_pops/projects/Project3App/Project_3_Api/project_3_api/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/alys/sei_ice_pops/projects/Project3App/Project_3_Api/project_3_api/node_modules/express/lib/router/route.js:137:13)
    at complete (/home/alys/sei_ice_pops/projects/Project3App/Project_3_Api/project_3_api/node_modules/passport/lib/middleware/authenticate.js:262:13)
    at /home/alys/sei_ice_pops/projects/Project3App/Project_3_Api/project_3_api/node_modules/passport/lib/middleware/authenticate.js:269:15
    at pass (/home/alys/sei_ice_pops/projects/Project3App/Project_3_Api/project_3_api/node_modules/passport/lib/authenticator.js:428:14)
    at Authenticator.transformAuthInfo (/home/alys/sei_ice_pops/projects/Project3App/Project_3_Api/project_3_api/node_modules/passport/lib/authenticator.js:450:5)
    at /home/alys/sei_ice_pops/projects/Project3App/Project_3_Api/project_3_api/node_modules/passport/lib/middleware/authenticate.js:266:22
    at IncomingMessage.req.login.req.logIn (/home/alys/sei_ice_pops/projects/Project3App/Project_3_Api/project_3_api/node_modules/passport/lib/http/request.js:45:13)
    at Strategy.strategy.success (/home/alys/sei_ice_pops/projects/Project3App/Project_3_Api/project_3_api/node_modules/passport/lib/middleware/authenticate.js:247:13)
```

**What is the problem you are trying to solve?**
Trying to create a Service document that is associated with a user.

**Expected behavior**
_A clear and concise description of what you expected to happen._
We get a 200 message and a return JSON object of the created document

**What is the actual behavior?**
_A clear and concise description of what actually happened._
(error as seen above, server error 500 and terminal error)

**Post any code you think might be relevant (one fenced block per file)**
Service Schema
```js
const serviceSchema = new Schema({
    name: {
        type: String,
        required: true,
        default: ''
    },
    type: {
        type: String,
        required: true,
        default: ''
    },
    owner: {
        type: Schema.Types.ObjectId,
        // required: true,
        ref: 'User'
    },
    rate: {
        type: Number,
        required: true,
        default: ''
    },
}, {
    timestamps: true
})
```
Service Route
```
// CREATE
// POST /services
// this WILL require authentication
router.post('/services', requireToken, (req, res, next) => {
	// set owner of new service to be current user
	req.body.example.owner = req.user.id

	Service.create(req.body.service)
		// respond to succesful `create` with status 201 and JSON of new "example"
		.then((service) => {
			res.status(201).json({ service: service.toObject() })
		})
		// if an error occurs, pass it off to our error handler
		// the error handler needs the error message and the `res` object so that it
		// can send an error message back to the client
		.catch(next)
})
```

postman request:
```
{
    "service": {
        "name": "Animal Psychic Reading",
        "type": "paranormal",
        "rate": 60
    }
}
```

**What is your best guess as to the source of the problem?**
A crossed authentication wire!

**What things have you already tried to solve the problem?**
adding in owner manually, trying different users

**Additional context**

**Paste a link to your repository here**
https://github.com/alysvolatile/Scrumptious-Bunch-API

**Comment by mattkeane-ga** [comment]
`req.body.example.owner` does not much the shape of the JSON you sent in the body of your request.

**Comment by alysarnau** [comment]
![me](https://user-images.githubusercontent.com/102048901/182686469-f6d4fc35-c819-47d5-b12d-67fa64860b9a.jpg)
Thank you, Matt! That resolved it.
