### ISSUE TITLE
globetrotters new rec activity

### ISSUE THREAD

**Issue by tylly** [sei-ec-remote/team-project-issues#80]
**Describe the bug**
_A clear and concise description of what the bug is._
when the user clicks the button, i would like a NewRecActivityModal component to show up only for the corresponding activity. components for all suggested are showing up, so the user just sees a modal for whatever the last recommended activity is because its on top of all of the others

**What is the problem you are trying to solve?**
trying to get only a modal for the corresponding activity to show up

**Expected behavior**
_A clear and concise description of what you expected to happen._
only show modal for corresponding activity

**What is the actual behavior?**
_A clear and concise description of what actually happened._
modals for all activities are layered on top of each other, with the last activity being on top

**Post any code you think might be relevant (one fenced block per file)**
```js
import React, { useState, useEffect } from "react";
import { DropdownButton, Modal } from "react-bootstrap";
import ActivityForm from "../shared/ActivityForm";
import { createActivity } from "../../api/activities";
import Dropdown from "react-bootstrap/Dropdown";
import { Link } from "react-router-dom";
import { Form, Button, Container } from "react-bootstrap";
import RecommendedList from "./RecommendedList";
import axios from "axios";
import NewRecActivityModal from "../activities/NewRecActivityModal";
const SearchActivityModal = (props) => {
  const { user, destination, show, handleClose, msgAlert, triggerRefresh } =
    props;
  const [value, setValue] = useState("important tourist attraction");
  const [activity, setActivity] = useState({ name: "" });
  const [recActivityModalShow, setRecActivityModalShow] = useState(false);
  const [recommendedListShow, setRecommendedListShow] = useState(false);
  const [places, setPlaces] = useState({
    data: { results: [] },
  });
  const handleSelect = (e) => {
    console.log(e);
    setValue(e);
  };
  console.log(value);

  useEffect(
    /* (sync) effect function */ () => {
      const func = async () => {
        let newPlaces = await axios.get(
          `https://api.tomtom.com/search/2/categorySearch/${value}.json?typeahead=true&lat=${destination.lat}&lon=${destination.lon}&view=Unified&relatedPois=off&key=9JyQb3r2IQDfXHOgwSTNBa8mkxAAuNAT`
        );
        console.log(newPlaces);
        setPlaces(newPlaces);
      };
      func();
    },
    /* dependencies */ [value]
  );

  //let places;

  //places = func();
  console.log(places.data.results);

  let items = places.data.results.map((i) => (
    <>
      <li>
        <Button
          id={i.id}
          onClick={() => {
            setRecActivityModalShow(true);
            console.log(places);
          }}
        >
          {i.poi.name}
        </Button>
      </li>
      <NewRecActivityModal
        user={user}
        destination={destination}
        show={recActivityModalShow}
        msgAlert={msgAlert}
        name={i.poi.name}
        address={i.address.freeformAddress}
        handleClose={() => setRecActivityModalShow(false)}
      />
    </>
  ));
  console.log(items);
  const handleChange = (e) => {
    setActivity((prevActivity) => {
      let value = e.target.value;
      const name = e.target.name;
      console.log(value);
      // console.log('this is the input type', e.target.type)

      const updatedActivity = {
        [name]: value,
      };
      return {
        ...prevActivity,
        ...updatedActivity,
      };
    });
  };

  const handleSubmit = (e) => {
    // e equals the event
    e.preventDefault();
    console.log(destination);
    createActivity(user, destination._id, activity)
      // if we're successful in the modal, we want the modal to close
      .then(() => handleClose())
      // send a success message to the user
      .then(() => {
        msgAlert({
          heading: "Oh Yeah!",
          message: "Great! This will be fun!",
          variant: "success",
        });
      })
      .then(() => triggerRefresh())
      // if there is an error, tell the user about it
      .catch(() =>
        msgAlert({
          heading: "Oh No!",
          message: "Something went wrong, please try again",
          variant: "danger",
        })
      );
  };

  let item = <h2>hey</h2>;
  return (
    <Modal show={show} onHide={handleClose}>
      {<h3>Search {value}</h3>}
      <Modal.Header closeButton />
      <Modal.Body>
        <Form>
          {/* <Dropdown>
          <Dropdown.Toggle variant="success" id="dropdown-basic">
            Dropdown Button
          </Dropdown.Toggle> */}
          <DropdownButton onSelect={handleSelect}>
            <Dropdown.Item eventKey="important tourist attraction">
              important tourist attraction
            </Dropdown.Item>
            <Dropdown.Item eventKey="museum">museum</Dropdown.Item>
            <Dropdown.Item eventKey="parks">parks</Dropdown.Item>
            <Dropdown.Item eventKey="natural tourist attraction">
              natural tourist attraction
            </Dropdown.Item>
            <Dropdown.Item eventKey="statues">statues</Dropdown.Item>
            <Dropdown.Item eventKey="sushi">sushi</Dropdown.Item>
            <Dropdown.Item eventKey="donut">timms suggestion</Dropdown.Item>
            <Dropdown.Item eventKey="mediterranean">
              mediterranean
            </Dropdown.Item>
            <Dropdown.Item eventKey="breweries">breweries</Dropdown.Item>
            <Dropdown.Item eventKey="dispensaries">dispensaries</Dropdown.Item>
            <Dropdown.Item eventKey="sports">sports</Dropdown.Item>
            <Dropdown.Item eventKey="gas stations">gas stations</Dropdown.Item>
            <Dropdown.Item eventKey="coffee">coffee</Dropdown.Item>
          </DropdownButton>
          {/* </Dropdown> */}
        </Form>
        {/* {user && destination.owner === user._id ? (
          <>
            <Button onClick={() => 
            {
                setRecommendedListShow(true)
                
            
            }}
            
            >Submit</Button>
          </>
        ) : null} */}
        <ul>
          {items}
          {/* <RecommendedList  style={{display:"none"}} items={items} /> */}
        </ul>
      </Modal.Body>
    </Modal>
  );
};

export default SearchActivityModal;

```

**What is your best guess as to the source of the problem?**

since modals are created for each activity in the loop, all of them are triggered to open by setRecActivityModalShow(true)

**What things have you already tried to solve the problem?**
not creating the modals in the loop, but i cant figure out how to pass the modal the correct data

**Additional context**

**Paste a link to your repository here**
https://github.com/tylly/project-3-react

**Comment by timmshinbone** [comment]
I see you have a hook that sets a specific activity, 
```js
const [activity, setActivity] = useState({ name: "" });
```
but when you call the modal, no activity is passed to it. I think that's the answer here. The way you open the modal needs to be reworked as follows:

1. clicking sets the current activity to whatever one was clicked
2. that activity is automatically associated with the modal with `activity={activity}`
3. THEN the modal opens and should contain the activity information

Try that and let me know how it goes/what changes

**Comment by tylly** [comment]
i got it! like this:
```js
import React, { useState, useEffect } from "react";
import { DropdownButton, Modal } from "react-bootstrap";
import ActivityForm from "../shared/ActivityForm";
import { createActivity } from "../../api/activities";
import Dropdown from "react-bootstrap/Dropdown";
import { Link } from "react-router-dom";
import { Form, Button, Container } from "react-bootstrap";
import RecommendedList from "./RecommendedList";
import axios from "axios";
import NewRecActivityModal from "../activities/NewRecActivityModal";
const SearchActivityModal = (props) => {
  const { user, destination, show, handleClose, msgAlert, triggerRefresh } =
    props;
  const [value, setValue] = useState("important tourist attraction");
  const [activity, setActivity] = useState({ name: "" });
  const [recActivityModalShow, setRecActivityModalShow] = useState(false);
  const [recommendedListShow, setRecommendedListShow] = useState(false);
  const [places, setPlaces] = useState({
    data: { results: [] },
  });
  const handleSelect = (e) => {
    console.log(e);
    setValue(e);
  };
  console.log(value);

  useEffect(() => {
      const func = async () => {
        let newPlaces = await axios.get(
          `https://api.tomtom.com/search/2/categorySearch/${value}.json?typeahead=true&lat=${destination.lat}&lon=${destination.lon}&view=Unified&relatedPois=off&key=9JyQb3r2IQDfXHOgwSTNBa8mkxAAuNAT`
        );
        console.log(newPlaces);
        setPlaces(newPlaces);
      };
      func();
    }, [value]
  );

  console.log(places.data.results);

  let items = places.data.results.map((i) => (
    <>
      <li>
        <Button
          id={i.id}
          onClick={() => {
            setActivity(i)
            setRecActivityModalShow(true);
            console.log(activity);
          }}
        >
          {i.poi.name}
        </Button>
      </li>
      <NewRecActivityModal
      key={i.id}
        user={user}
        destination={destination}
        show={recActivityModalShow}
        msgAlert={msgAlert}
        activity={activity}
        handleClose={() => setRecActivityModalShow(false)}
      />
    </>
  ));
  console.log(items);
  const handleChange = (e) => {
    setActivity((prevActivity) => {
      let value = e.target.value;
      const name = e.target.name;
      console.log(value);
      // console.log('this is the input type', e.target.type)

      const updatedActivity = {
        [name]: value,
      };
      return {
        ...prevActivity,
        ...updatedActivity,
      };
    });
  };

  const handleSubmit = (e) => {
    // e equals the event
    e.preventDefault();
    console.log(destination);
    createActivity(user, destination._id, activity)
      // if we're successful in the modal, we want the modal to close
      .then(() => handleClose())
      // send a success message to the user
      .then(() => {
        msgAlert({
          heading: "Oh Yeah!",
          message: "Great! This will be fun!",
          variant: "success",
        });
      })
      .then(() => triggerRefresh())
      // if there is an error, tell the user about it
      .catch(() =>
        msgAlert({
          heading: "Oh No!",
          message: "Something went wrong, please try again",
          variant: "danger",
        })
      );
  };

  let item = <h2>hey</h2>;
  return (
    <Modal show={show} onHide={handleClose}>
      {<h3>Search {value}</h3>}
      <Modal.Header closeButton />
      <Modal.Body>
        <Form>
          {/* <Dropdown>
          <Dropdown.Toggle variant="success" id="dropdown-basic">
            Dropdown Button
          </Dropdown.Toggle> */}
          <DropdownButton onSelect={handleSelect}>
            <Dropdown.Item eventKey="important tourist attraction">
              important tourist attraction
            </Dropdown.Item>
            <Dropdown.Item eventKey="museum">museum</Dropdown.Item>
            <Dropdown.Item eventKey="parks">parks</Dropdown.Item>
            <Dropdown.Item eventKey="natural tourist attraction">
              natural tourist attraction
            </Dropdown.Item>
            <Dropdown.Item eventKey="statues">statues</Dropdown.Item>
            <Dropdown.Item eventKey="sushi">sushi</Dropdown.Item>
            <Dropdown.Item eventKey="donut">timms suggestion</Dropdown.Item>
            <Dropdown.Item eventKey="mediterranean">
              mediterranean
            </Dropdown.Item>
            <Dropdown.Item eventKey="breweries">breweries</Dropdown.Item>
            <Dropdown.Item eventKey="dispensaries">dispensaries</Dropdown.Item>
            <Dropdown.Item eventKey="sports">sports</Dropdown.Item>
            <Dropdown.Item eventKey="gas stations">gas stations</Dropdown.Item>
            <Dropdown.Item eventKey="coffee">coffee</Dropdown.Item>
          </DropdownButton>
          {/* </Dropdown> */}
        </Form>
        {/* {user && destination.owner === user._id ? (
          <>
            <Button onClick={() => 
            {
                setRecommendedListShow(true)
                
            
            }}
            
            >Submit</Button>
          </>
        ) : null} */}
        <ul>
          {items}
          {/* <RecommendedList  style={{display:"none"}} items={items} /> */}
        </ul>
      </Modal.Body>
    </Modal>
  );
};

export default SearchActivityModal;
```

I'm pretty sure there are multiple modals showing up but at least they all correspond to the correct activity.

**Comment by tylly** [comment]
my next issue is my submit isnot working
```
import React, { useState, useEffect } from "react";
import { DropdownButton, Modal } from "react-bootstrap";
import ActivityForm from "../shared/ActivityForm";
import { createActivity } from "../../api/activities";
import Dropdown from "react-bootstrap/Dropdown";
import { Link } from "react-router-dom";
import { Form, Button, Container } from "react-bootstrap";
import RecommendedList from "./RecommendedList";
import axios from "axios";
import NewRecActivityModal from "../activities/NewRecActivityModal";
const SearchActivityModal = (props) => {
  const { user, destination, show, handleClose, msgAlert, triggerRefresh } =
    props;
  const [value, setValue] = useState("important tourist attraction");
  const [activity, setActivity] = useState({ name: "" });
  const [recActivityModalShow, setRecActivityModalShow] = useState(false);
  const [recommendedListShow, setRecommendedListShow] = useState(false);
  const [places, setPlaces] = useState({
    data: { results: [] },
  });
  const handleSelect = (e) => {
    console.log(e);
    setValue(e);
  };
  console.log(value);

  useEffect(() => {
      const func = async () => {
        let newPlaces = await axios.get(
          `https://api.tomtom.com/search/2/categorySearch/${value}.json?typeahead=true&lat=${destination.lat}&lon=${destination.lon}&view=Unified&relatedPois=off&key=9JyQb3r2IQDfXHOgwSTNBa8mkxAAuNAT`
        );
        console.log(newPlaces);
        setPlaces(newPlaces);
      };
      func();
    }, [value]
  );

  console.log(places.data.results);

  let items = places.data.results.map((i) => (
    <>
      <li>
        <Button
          id={i.id}
          onClick={() => {
            setActivity(i)
            setRecActivityModalShow(true);
            console.log(activity);
          }}
        >
          {i.poi.name}
        </Button>
      </li>
      <NewRecActivityModal
      key={i.id}
        user={user}
        destination={destination}
        show={recActivityModalShow}
        msgAlert={msgAlert}
        activity={activity}
        handleClose={() => setRecActivityModalShow(false)}
      />
    </>
  ));
  console.log(items);
  const handleChange = (e) => {
    setActivity((prevActivity) => {
      let value = e.target.value;
      const name = e.target.name;
      console.log(value);
      // console.log('this is the input type', e.target.type)

      const updatedActivity = {
        [name]: value,
      };
      return {
        ...prevActivity,
        ...updatedActivity,
      };
    });
  };

  const handleSubmit = (e) => {
    // e equals the event
    e.preventDefault();
    console.log(destination);
    createActivity(user, destination._id, activity)
      // if we're successful in the modal, we want the modal to close
      .then(() => handleClose())
      // send a success message to the user
      .then(() => {
        msgAlert({
          heading: "Oh Yeah!",
          message: "Great! This will be fun!",
          variant: "success",
        });
      })
      .then(() => triggerRefresh())
      // if there is an error, tell the user about it
      .catch(() =>
        msgAlert({
          heading: "Oh No!",
          message: "Something went wrong, please try again",
          variant: "danger",
        })
      );
  };

  let item = <h2>hey</h2>;
  return (
    <Modal show={show} onHide={handleClose}>
      {<h3>Search {value}</h3>}
      <Modal.Header closeButton />
      <Modal.Body>
        <Form>
          {/* <Dropdown>
          <Dropdown.Toggle variant="success" id="dropdown-basic">
            Dropdown Button
          </Dropdown.Toggle> */}
          <DropdownButton onSelect={handleSelect}>
            <Dropdown.Item eventKey="important tourist attraction">
              important tourist attraction
            </Dropdown.Item>
            <Dropdown.Item eventKey="museum">museum</Dropdown.Item>
            <Dropdown.Item eventKey="parks">parks</Dropdown.Item>
            <Dropdown.Item eventKey="natural tourist attraction">
              natural tourist attraction
            </Dropdown.Item>
            <Dropdown.Item eventKey="statues">statues</Dropdown.Item>
            <Dropdown.Item eventKey="sushi">sushi</Dropdown.Item>
            <Dropdown.Item eventKey="donut">timms suggestion</Dropdown.Item>
            <Dropdown.Item eventKey="mediterranean">
              mediterranean
            </Dropdown.Item>
            <Dropdown.Item eventKey="breweries">breweries</Dropdown.Item>
            <Dropdown.Item eventKey="dispensaries">dispensaries</Dropdown.Item>
            <Dropdown.Item eventKey="sports">sports</Dropdown.Item>
            <Dropdown.Item eventKey="gas stations">gas stations</Dropdown.Item>
            <Dropdown.Item eventKey="coffee">coffee</Dropdown.Item>
          </DropdownButton>
          {/* </Dropdown> */}
        </Form>
        {/* {user && destination.owner === user._id ? (
          <>
            <Button onClick={() => 
            {
                setRecommendedListShow(true)
                
            
            }}
            
            >Submit</Button>
          </>
        ) : null} */}
        <ul>
          {items}
          {/* <RecommendedList  style={{display:"none"}} items={items} /> */}
        </ul>
      </Modal.Body>
    </Modal>
  );
};

export default SearchActivityModal;

```
```
import React, { useState, useEffect } from "react";
import { DropdownButton, Modal } from "react-bootstrap";
import ActivityForm from "../shared/ActivityForm";
import { createActivity } from "../../api/activities";
import Dropdown from "react-bootstrap/Dropdown";
import { Link } from "react-router-dom";
import { Form, Button, Container } from "react-bootstrap";
import RecommendedList from "./RecommendedList";
import axios from "axios";
import NewRecActivityModal from "../activities/NewRecActivityModal";
const SearchActivityModal = (props) => {
  const { user, destination, show, handleClose, msgAlert, triggerRefresh } =
    props;
  const [value, setValue] = useState("important tourist attraction");
  const [activity, setActivity] = useState({ name: "" });
  const [recActivityModalShow, setRecActivityModalShow] = useState(false);
  const [recommendedListShow, setRecommendedListShow] = useState(false);
  const [places, setPlaces] = useState({
    data: { results: [] },
  });
  const handleSelect = (e) => {
    console.log(e);
    setValue(e);
  };
  console.log(value);

  useEffect(() => {
      const func = async () => {
        let newPlaces = await axios.get(
          `https://api.tomtom.com/search/2/categorySearch/${value}.json?typeahead=true&lat=${destination.lat}&lon=${destination.lon}&view=Unified&relatedPois=off&key=9JyQb3r2IQDfXHOgwSTNBa8mkxAAuNAT`
        );
        console.log(newPlaces);
        setPlaces(newPlaces);
      };
      func();
    }, [value]
  );

  console.log(places.data.results);

  let items = places.data.results.map((i) => (
    <>
      <li>
        <Button
          id={i.id}
          onClick={() => {
            setActivity(i)
            setRecActivityModalShow(true);
            console.log(activity);
          }}
        >
          {i.poi.name}
        </Button>
      </li>
      <NewRecActivityModal
      key={i.id}
        user={user}
        destination={destination}
        show={recActivityModalShow}
        msgAlert={msgAlert}
        activity={activity}
        handleClose={() => setRecActivityModalShow(false)}
      />
    </>
  ));
  console.log(items);
  const handleChange = (e) => {
    setActivity((prevActivity) => {
      let value = e.target.value;
      const name = e.target.name;
      console.log(value);
      // console.log('this is the input type', e.target.type)

      const updatedActivity = {
        [name]: value,
      };
      return {
        ...prevActivity,
        ...updatedActivity,
      };
    });
  };

  const handleSubmit = (e) => {
    // e equals the event
    e.preventDefault();
    console.log(destination);
    createActivity(user, destination._id, activity)
      // if we're successful in the modal, we want the modal to close
      .then(() => handleClose())
      // send a success message to the user
      .then(() => {
        msgAlert({
          heading: "Oh Yeah!",
          message: "Great! This will be fun!",
          variant: "success",
        });
      })
      .then(() => triggerRefresh())
      // if there is an error, tell the user about it
      .catch(() =>
        msgAlert({
          heading: "Oh No!",
          message: "Something went wrong, please try again",
          variant: "danger",
        })
      );
  };

  let item = <h2>hey</h2>;
  return (
    <Modal show={show} onHide={handleClose}>
      {<h3>Search {value}</h3>}
      <Modal.Header closeButton />
      <Modal.Body>
        <Form>
          {/* <Dropdown>
          <Dropdown.Toggle variant="success" id="dropdown-basic">
            Dropdown Button
          </Dropdown.Toggle> */}
          <DropdownButton onSelect={handleSelect}>
            <Dropdown.Item eventKey="important tourist attraction">
              important tourist attraction
            </Dropdown.Item>
            <Dropdown.Item eventKey="museum">museum</Dropdown.Item>
            <Dropdown.Item eventKey="parks">parks</Dropdown.Item>
            <Dropdown.Item eventKey="natural tourist attraction">
              natural tourist attraction
            </Dropdown.Item>
            <Dropdown.Item eventKey="statues">statues</Dropdown.Item>
            <Dropdown.Item eventKey="sushi">sushi</Dropdown.Item>
            <Dropdown.Item eventKey="donut">timms suggestion</Dropdown.Item>
            <Dropdown.Item eventKey="mediterranean">
              mediterranean
            </Dropdown.Item>
            <Dropdown.Item eventKey="breweries">breweries</Dropdown.Item>
            <Dropdown.Item eventKey="dispensaries">dispensaries</Dropdown.Item>
            <Dropdown.Item eventKey="sports">sports</Dropdown.Item>
            <Dropdown.Item eventKey="gas stations">gas stations</Dropdown.Item>
            <Dropdown.Item eventKey="coffee">coffee</Dropdown.Item>
          </DropdownButton>
          {/* </Dropdown> */}
        </Form>
        {/* {user && destination.owner === user._id ? (
          <>
            <Button onClick={() => 
            {
                setRecommendedListShow(true)
                
            
            }}
            
            >Submit</Button>
          </>
        ) : null} */}
        <ul>
          {items}
          {/* <RecommendedList  style={{display:"none"}} items={items} /> */}
        </ul>
      </Modal.Body>
    </Modal>
  );
};

export default SearchActivityModal;


```

**Comment by tylly** [comment]
my next issue is my submit isnt working

```js
import React, { useState } from 'react'
import { Modal } from 'react-bootstrap'
import RecActivityForm from '../shared/RecActivityForm'
import { createActivity } from '../../api/activities'


const NewRecActivityModal = (props) => {
    const { 
        user, destination, show, handleClose, msgAlert, triggerRefresh
    } = props
console.log(props)
    const [activity, setActivity] = useState({})

    // console.log('destination in edit modal', destination)

    const handleChange = (e) => {
        setActivity(prevActivity => {
            let value = e.target.value
            let name = e.target.name
            console.log(value)
            // console.log('this is the input type', e.target.type)

            const updatedActivity = {
                [name]: value
            }
            return {
                ...prevActivity,
                ...updatedActivity
            }
        })
    }

    const handleSubmit = (e) => {
        // e equals the event
        e.preventDefault()
        console.log(destination)
        createActivity(user, destination._id, activity)
            // if we're successful in the modal, we want the modal to close
            .then(() => handleClose())
            // send a success message to the user
            .then(() => {
                msgAlert({
                    heading: 'Oh Yeah!',
                    message: 'Great! This will be fun!',
                    variant: 'success'
                })
            })
            .then(() => triggerRefresh())
            // if there is an error, tell the user about it
            .catch(() => 
                msgAlert({
                    heading: 'Oh No!',
                    message: 'Something went wrong, please try again',
                    variant: 'danger'
                })
            )
    }

    return (
        <Modal show={show} onHide={handleClose}>
            <Modal.Header closeButton />
            <Modal.Body>
                <RecActivityForm 
                    activity={props.activity}
                    handleChange={handleChange}
                    handleSubmit={handleSubmit}
                    heading="Plan Something To Do!"
                />
            </Modal.Body>
        </Modal>
    )
}

export default NewRecActivityModal
```

```js
import { Form,Button,Container} from 'react-bootstrap'
import React, { useState } from 'react'


const RecActivityForm = (props) => {
    const {activity, handleChange, handleSubmit, heading} = props
    console.log(props)
    return (
            <Container className="justify-content-center">
                <h3>{heading}</h3>
                <Form onSubmit={handleSubmit}>
                    <Form.Label htmlFor="name">Name</Form.Label>
                    <Form.Control
                        placeholder={props.activity.poi.name}
                        name="name"
                        id="name"
                        value={props.activity.poi.name}
                        onChange={ handleChange }
                    />
                    <Form.Label htmlFor="address" className='mt-2'>Address</Form.Label>
                    <Form.Control
                        placeholder={props.activity.address.freeformAddress}
                        name="address"
                        id="address"
                        value={ props.activity.address.freeformAddress }
                        onChange={ handleChange }
                    />
                    <Form.Label htmlFor="schedule" className='mt-2'>Schedule</Form.Label>
                    <Form.Control
                        placeholder="when?"
                        name="schedule"
                        id="schedule"
                        value={ activity.schedule}
                        onChange={ handleChange }
                 />
                 <Form.Label htmlFor="priority" className='mt-2'>How badly do you want to do this?</Form.Label>
                    <Form.Range 
                    name="priority"
                    id="priority"
                    value={activity.priority}
                    onChange={handleChange}
                    />
                  
                    <Button type="submit">Submit</Button>
                </Form>
            </Container>
        )
}

export default RecActivityForm
```

**Comment by timmshinbone** [comment]
Awesome, nice work getting it going, what's the error you get when trying to submit?

**Comment by tylly** [comment]
```
 09:17:25 GMT-0600 (Mountain Daylight Time):
Error: Destination validation failed: activities.0.name: Path `name` is required.
    at ValidationError.inspect (/Users/jamesadams/sei/projects/project-3-planning/project-3/project-3-mongoose-express/node_modules/mongoose/lib/error/validation.js:48:26)
    at formatValue (node:internal/util/inspect:782:19)
    at inspect (node:internal/util/inspect:347:10)
    at formatWithOptionsInternal (node:internal/util/inspect:2167:40)
    at formatWithOptions (node:internal/util/inspect:2029:10)
    at console.value (node:internal/console/constructor:332:14)
    at console.warn (node:internal/console/constructor:365:61)
    at module.exports (/Users/jamesadams/sei/projects/project-3-planning/project-3/project-3-mongoose-express/lib/error_handler.js:12:11)
    at Layer.handle_error (/Users/jamesadams/sei/projects/project-3-planning/project-3/project-3-mongoose-express/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/Users/jamesadams/sei/projects/project-3-planning/project-3/project-3-mongoose-express/node_modules/express/lib/router/index.js:315:13) {
  errors: {
    'activities.0.name': ValidatorError: Path `name` is required.
        at validate (/Users/jamesadams/sei/projects/project-3-planning/project-3/project-3-mongoose-express/node_modules/mongoose/lib/schematype.js:1277:13)
        at /Users/jamesadams/sei/projects/project-3-planning/project-3/project-3-mongoose-express/node_modules/mongoose/lib/schematype.js:1260:7
        at Array.forEach (<anonymous>)
        at SchemaType.doValidate (/Users/jamesadams/sei/projects/project-3-planning/project-3/project-3-mongoose-express/node_modules/mongoose/lib/schematype.js:1210:14)
        at /Users/jamesadams/sei/projects/project-3-planning/project-3/project-3-mongoose-express/node_modules/mongoose/lib/document.js:2704:18
        at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
      properties: [Object],
      kind: 'required',
      path: 'name',
      value: undefined,
      reason: undefined,
      [Symbol(mongoose:validatorError)]: true
    }
  },
  _message: 'Destination validation failed'
}
```

**Comment by timmshinbone** [comment]
ok, send me what the console log of the data you're trying to send looks like

**Comment by tylly** [comment]
I changed the console log in the handleSubmit in NewRecActivityModal to log props.activity and i got this

```
{type: 'POI', id: '840269001155257', score: 7.7891454697, dist: 47015.47531935788, info: 'search:ta:840269001155257-US', …}
address: {streetNumber: '606', streetName: 'Water Street', municipality: 'Cheboygan', countrySecondarySubdivision: 'Cheboygan', countrySubdivision: 'MI', …}
dist: 47015.47531935788
entryPoints: [{…}]
id: "840269001155257"
info: "search:ta:840269001155257-US"
poi: {name: 'Cheboygan Front Range Lighthouse', categorySet: Array(1), categories: Array(2), classifications: Array(1)}
position: {lat: 45.64738, lon: -84.47279}
score: 7.7891454697
type: "POI"
viewport: {topLeftPoint: {…}, btmRightPoint: {…}}
[[Prototype]]: Object
```

**Comment by tylly** [comment]
RecActivityForm now looks like this
```js

import { Form,Button,Container} from 'react-bootstrap'
import React, { useState } from 'react'


const RecActivityForm = (props) => {
    const {activity, handleChange, handleSubmit, heading} = props
    console.log(props)
    return (
            <Container className="justify-content-center">
                <h3>{heading}</h3>
                <Form onSubmit={handleSubmit}>
                    <Form.Label htmlFor="name">Name</Form.Label>
                    <Form.Control
                        placeholder={props.activity.poi.name}
                        name="name"
                        id="name"
                        value={props.activity.poi.name}
                        onChange={ handleChange }
                    />
                    <Form.Label htmlFor="address" className='mt-2'>Address</Form.Label>
                    <Form.Control
                        placeholder={props.activity.address.freeformAddress}
                        name="address"
                        id="address"
                        value={ props.activity.address.freeformAddress }
                        onChange={ handleChange }
                    />
                    <Form.Label htmlFor="schedule" className='mt-2'>Schedule</Form.Label>
                    <Form.Control
                        placeholder="when?"
                        name="schedule"
                        id="schedule"
                        value={ activity.schedule}
                        onChange={ handleChange }
                 />
                 <Form.Label htmlFor="priority" className='mt-2'>How badly do you want to do this?</Form.Label>
                    <Form.Range 
                    name="priority"
                    id="priority"
                    value={activity.priority}
                    onChange={handleChange}
                    />
                  
                    <Button type="submit">Submit</Button>
                </Form>
            </Container>
        )
}

export default RecActivityForm

```

**Comment by tylly** [comment]
also i changed  search activity modal so that the NewRecActivityModal is just created in the return and not for each activity in the .map which works

**Comment by tylly** [comment]
```
    'activities.0.address': CastError: Cast to string failed for value "{
      streetNumber: '2576',
      streetName: 'Crossing Circle',
      municipality: 'Garfield',
      countrySecondarySubdivision: 'Grand Traverse',
      countrySubdivision: 'MI',
      countrySubdivisionName: 'Michigan',
      postalCode: '49684',
      extendedPostalCode: '49684-7955',
      countryCode: 'US',
      country: 'United States',
      countryCodeISO3: 'USA',
      freeformAddress: '2576 Crossing Circle, Traverse City, MI 49684',
      localName: 'Traverse City'
    }" (type Object) at path "address"
```
this should just be sending it the freeforAddress but its sending the whole object

**Comment by timmshinbone** [comment]
Hm, let's look at this together in a breakout room after lunch

**Comment by tylly** [comment]
word
